반경 내 주차장 조회 기능 구현
parkingkim/parking-BE pull request #13
Opened 2024-02-06 08:52 UTC by youngh0

## 👍관련 이슈
- close: #10 

## 🤔세부 내용
`GET /parkings?정렬조건 `
API 구현했습니다. 

- repository 의 JPQL 부분을 보면 MYSQL 에서 지원해주는 ST_CONTAINS, ST_BUFFER, ST_DISTANCE_SPHERE 를 사용했습니다.
  - `ST_BUFFER(POINT, radius)`: POINT 중점으로 부터 반지름이 radius 인 원을 생성해줍니다.
  - `ST_CONTAINS(원, POINT)`: POINT 가 원 안에 있는지 판단합니다. 여기서 원은 ST_BUFFER 로 생성된 원을 사용하도록 했습니다.
  - `ST_DISTANCE_SPHERE(POINT, POINT)`: POINT 간의 거리 차이를 계산합니다. 이 함수는 가까운 순으로 정렬조건을 줬을 때 사용합니다. 

## 🫵리뷰 중점사항
- 필터링 하는 부분을 별도의 ParkingDomainService 로 분리했습니다. (네이밍은 생각이 안나서 일단 ParkingDomainService 로 했어요..)
  - 필터링 하는 조건이 추가되면 DB 와 통신하는 service 를 건드리지 않고 domainService 만 변경해서 요구사항을 충족할 수 있을것같아 분리해봤습니다.

- 필터링 조건 중 cardEnabled는 전에 얘기한대로 애매한 부분이 있어서 제외했습니다.
- 필터링 조건 중 유.무료 부분은 요금계산 로직이 완료되면 그걸 토대로 필터링 조건 추가하면 될 것 같습니다.

- 응답 값에서 예상 요금, 도보 시간, 즐겨찾기는 아직 구현되지 않은 부분이라 null 을 반환하도록 했습니다.

2024-02-17 05:55 UTC, jundonghyuk approved these changes
각각 커멘트 남겼씁니다 ~_~

2024-02-17 05:55 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/parking/ParkingService.java
> +    private final ParkingRepository parkingRepository;
라인 분리 어떨까요?

2024-02-17 05:55 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/parking/ParkingService.java
> +    public ParkingLotsResponse findParkingLots(ParkingQueryRequest parkingQueryRequest) {
트랜잭셔널이 없어도될까요 ?

2024-02-17 06:20 UTC, This2sho commented on src/main/java/com/example/parking/application/parking/dto/ParkingLotsResponse.java
> +@Getter
@NoArgsConstructor(access = AccessLevel.PRIVATE)

2024-02-17 06:31 UTC, This2sho reviewed
굳이요 ~ 👍

2024-02-17 06:31 UTC, This2sho commented on src/main/java/com/example/parking/application/parking/dto/ParkingLotsResponse.java
> +@Getter
@NoArgsConstructor(access = AccessLevel.PRIVATE)

2024-02-17 06:31 UTC, This2sho commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingQueryArgumentResolver.java
> +public class ParkingQueryArgumentResolver implements HandlerMethodArgumentResolver {
👍

2024-03-14 04:32 UTC, youngh0 commented
- 사용자 조회조건 중 payType 이 주차장의 payType 에 포함되는지 확인하는 필터링 기능 구현
- 예상 요금 계산 로직 호출하여 요금 계산 기능 추가
- 주차장과 목적지 간 도보 예상 시간 계산 기능 구현
  - 주차장과 목적지 사이 거리를 km 로 구한 뒤, 이를 도보 평균 속도 5km 로 나누어 구했습니다.
  - 소수점의 경우 넉넉하게 올림으로 처리했습니다.

2024-03-22 13:01 UTC, youngh0 commented
[커밋 목록](https://github.com/parkingkim/parking-BE/pull/13/files/4c780fcdd075c5608e1151b44218eaa005f7d23e..00353107287a611d8b9c6767e927dac58f9ab866)

- query parameter 중 하나라도 Null 이면 기본 값을 가진 객체 반환하도록 했습니다. 
  - null 체크하고, 배열을 바꾸는 코드는 절차지향적으로 짤 수 밖에 없더라구요..

- ParkingSearchConditionRequest 의 기본 값을 설정할 때 enum(ParkingType, OperationType, payType) 의 원소들을 List<String> 형태로 어떻게 들고올지 여러분 의견이 궁금합니다.

  현재는 기본값을 설정할 때 각 enum(ParkingType, OperationType, payType) 에 getAllValues() 메서드를 정의해서 모든 원소를 List<String> 으로 반환하도록 하여 사용했습니다. 그래서 ParkingSearchConditionRequest 의 base() 메서드를 보시면 이를 활용하고 있는데요. 이렇게 사용한 이유는 enum 에 원소가 하나 추가될 경우 enum 에만 원소를 추가하면 ParkingSearchConditionRequest 를 손댈 필요가 없기 때문입니다.

  그런데, 저 enum 의 원소가 바뀔일은 거의 없을 거 같아서 ParkingSearchConditionRequest 와 enum 의 의존성을 아예 끊어서 ParkingSearchConditionRequest 에서 바로 List.of("노상", "노외") 이렇게 기본값을 설정하는 것도 좋아보이더라구요. 

  뭐가 더 괜찮아 보이시나여??

2024-03-26 18:55 UTC, This2sho requested changes
고생하셨습니다 영호씨
리뷰 남겼어여 확인부탁드려요

2024-03-26 18:55 UTC, This2sho commented on src/main/java/com/example/parking/domain/parking/PayType.java
> +    public static List<PayType> collectMatch(List<String> descriptions) {
이게 싫으면 `SearchConditionAvailable` 인터페이스에는 필요한 메서드만 두고 `SearchConditionMapper`에 Enum <-> String 간 변환 로직 둬도 괜찮을 거 같아여. 
아래는 생각해본 예시임다,

```java
public interface SearchConditionAvailable {

    String getDescription();

    <E extends SearchConditionAvailable> E getDefault();

    <E extends SearchConditionAvailable> E[] values();
}
```

```java
public class SearchConditionMapper {

    public static  <E extends SearchConditionAvailable> List<E> toEnums(E sc, List<String> descriptions) {
        return descriptions.stream()
                .map(description -> toEnum(sc, description))
                .toList();
    }

    public static <E extends SearchConditionAvailable> E toEnum(E sc, String description) {
        return (E) Arrays.stream(sc.values())
                .filter(e -> description.startsWith(sc.getDescription()))
                .findAny()
                .orElse(sc.getDefault());
    }

    public static <E extends SearchConditionAvailable> List<String> toStrings(E sc) {
        return Arrays.stream(sc.values())
                .filter(e -> e != sc.getDefault())
                .map(e -> ((SearchConditionAvailable) e).getDescription())
                .toList();
    }
}

```

2024-03-26 18:55 UTC, This2sho commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
`ParkingDomainService` 역할이 짬뽕된거 같아여
이름은 `Domain`, 어노테이션은 `Component`라서 도메인 서비스 같아 보이지만
패키지는 `application`에 있고 반환도 `response` 반환하고 있어서 어플리케이션 서비스 같이도 보여여
하나로 맞춰주셨으면 합니다

2024-03-26 18:55 UTC, This2sho commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingMemberId.java
> +public @interface ParkingMemberId {
`MemberAuth` 랑 역할이 동일한거 같은데
무슨 차이인가여?

2024-03-26 18:55 UTC, This2sho commented on src/main/java/com/example/parking/application/parking/dto/ParkingSearchConditionRequest.java
> +    private final String feeTypes;
유료, 무료 주차장 둘 다 보는 방법은 없는거야?

2024-03-27 05:15 UTC, jundonghyuk approved these changes

2024-03-27 05:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingSearchConditionArgumentResolver.java
> +    private List<String> toCollection(String[] parameters) {
toList()는 어때요 ?

2024-03-27 05:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
> +            Fee fee = parkingFeeCalculator.calculateParkingFee(parking, now, now.plusHours(hours));
저의 사랑스러운 아이가 들어가 있군요

2024-03-27 05:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
> +public class ParkingDomainService {
먼가 따로 분리해야했을까? 라는 생각이 들긴합니다 ! 이유가 있을까요 ?

2024-03-27 05:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/Parking.java
> +    }
계산로직이군여

2024-03-27 06:01 UTC, This2sho commented on src/main/java/com/example/parking/domain/parking/Parking.java
> +    }
그러게여 `ParkingFeeCalculator`처럼 목적지까지 거리나 시간 측정하는거 만들어서 빼도 될거 같아여

2024-03-27 13:15 UTC, youngh0 commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingMemberId.java
> +public @interface ParkingMemberId {
기존의 MemberAuth 는 잘못된 인증 정보면 예외를 던지는데 주차장 조회 기능에선 memberId 가 없으면 즐겨찾기 값을 전부 다 false 로 반환해야됩니다.

그래서 기존 MemberAuth의 잘못된 인증정보 시 예외던지는 코드를 주차장 조회 기능 때문에 null 을 반환하게 하면 MemberAuth 를 사용하고 있는 다른 로직에서 반환된 값의 null 체크를 하고 예외처리를 해야되기 때문에 예외 말고 null 을 반환하도록 새로 만들었습니다.

2024-03-27 13:17 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/Parking.java
> +    }
출발 위치 정보를 받고 주차장까지의 도보 예상 시간을 구하는 책임이라 Parking 에 있어도 자연스럽다고 생각했는데 별도의 Calculator 가 낫다고 생각하시나여??

2024-03-27 13:19 UTC, youngh0 commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
조회 조건에 맞게 필터링하는 절차지향적인 로직이라 별도의 Service 를 만들어서 ParkingService 를 조금 더 간결하게 해보려고 했는데 ParkingService 내부 private 메서드로 수정하는게 더 나을까요??

2024-03-27 13:19 UTC, youngh0 commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
> +public class ParkingDomainService {
호이 리뷰에 커멘트 달았슴다~

2024-03-27 13:23 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/OperationType.java
> +    public static List<String> getAllValues() {
어떤식으로 가능할지를 몰라서 못했는데 감사합니다~

2024-03-27 13:23 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/PayType.java
> +    public static List<PayType> collectMatch(List<String> descriptions) {
이것도 어떤식으로 코드를 짜야될지 몰라서.. 감사합니다 ㅎ

2024-03-27 16:40 UTC, youngh0 commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingSearchConditionArgumentResolver.java
> +    private List<String> toCollection(String[] parameters) {
고민했었는데 toList로 바꿀게여 ㅋㅋㅋㅋ

2024-03-27 17:11 UTC, youngh0 commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
List<Parking> 을 응답 dto 로 만들기 위해서 예상 요금, 도보 시간 계산, 즐겨 찾기 유무 확인해서 만드는 로직이 절차지향적이라 이 메서드를 ParkingService 의 private 메서드로 옮길지 ParkingApplicationService 에 둘지 계속 고민되네여,, 뭐가 더 괜찮아보이시나여?

2024-03-27 17:30 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/OperationType.java
> +    public static List<String> getAllValues() {
적용했습니다~

2024-03-27 17:30 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/PayType.java
> +    public static List<PayType> collectMatch(List<String> descriptions) {
적용했습니다~

2024-03-27 17:30 UTC, youngh0 commented on src/main/java/com/example/parking/application/parking/dto/ParkingSearchConditionRequest.java
> +    private final String feeTypes;
적용했습니다~

2024-03-27 17:31 UTC, youngh0 commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
> +            Fee fee = parkingFeeCalculator.calculateParkingFee(parking, now, now.plusHours(hours));
야무지더라구요

2024-03-27 18:08 UTC, This2sho commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingMemberId.java
> +public @interface ParkingMemberId {
같은 목적의 어노테이션을 두개로 늘리기 보다는 
아래처럼 필드를 추가해주고
```java
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface MemberAuth {
    boolean required() default true;
}
```

아규먼트 리졸버에서 required 값을 판단해서 아래처럼 내려주면 될 거 같습니다
```java
@Override
    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
                                  NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
        MemberAuth memberAuth = memberAuthFrom(parameter);
        if (memberAuth.required()) {
            String sessionId = webRequest.getHeader(JSESSIONID);
            MemberSession session = authService.findSession(sessionId);
            return session.getMemberId();
        }
        return null;
    }
    
    private MemberAuth memberAuthFrom(MethodParameter parameter) {
        return parameter.getParameterAnnotation(MemberAuth.class);
    }
```

2024-03-27 18:17 UTC, This2sho commented on src/main/java/com/example/parking/application/parking/ParkingDomainService.java
새로 서비스를 나눠서 구현한건 좋은 거 같습니다.
그렇지만, 조회 조건에 맞게 필터링하는 건 `ParkingFilterService` 같은 도메인 서비스를 두고 `ParkingResponse`로 변환해주는 코드는 Application Service 내부에 private 메소드로 둬도 괜찮을 거 같아여

2024-03-28 04:29 UTC, youngh0 commented on src/main/java/com/example/parking/config/argumentresolver/parking/ParkingMemberId.java
> +public @interface ParkingMemberId {
오 이건 생각 못했는데 아이디어 감사합니다 ㅎ

2024-04-03 05:07 UTC, This2sho approved these changes
긴 과정 고생하셨습니다 영호씨 👍

2024-04-03 05:07 UTC, merged