주차요금을 계산한다.
parkingkim/parking-BE pull request #29
Opened 2024-02-20 06:18 UTC by jundonghyuk

## 👍관련 이슈
- close: #28 

## 🤔세부 내용
주차시간에 따른 요금 계산하는 기능을 구현했습니다.
자세한 구현 방법은 #28 을 참고해주세요.

## 🫵리뷰 중점사항
알아보기 쉽도록 테스트케이스마다 어떤 상황에서 결과가 어떻게 도출 되는지 주석을 적어놨습니다.
테스트케이스 계산 결과가 틀렸거나, 또 다른 엣지케이스가 있다면 제보해주시면 감사하겠습니다.

2024-02-24 08:34 UTC, youngh0 requested changes
복잡한 로직인데 고생하셨습니다! 👍

요금 계산하는게 어느 정도 절차적이다 보니 별도의 Calculator 로 뺀거 전 좋아보입니다!

사소한 코멘트 몇 개 남겼습니다~

2024-02-24 08:34 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/ParkingFeeCalculator.java
> +public class ParkingFeeCalculator {
일부러 빈 등록을 안하신건가요??

2024-02-24 08:34 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/ParkingFeeCalculator.java
> +    public Fee calculateParkingFee(Parking parking, LocalDateTime beginTime, LocalDateTime endTime) {
혹시 Fee 말고 int 를 반환하는건 어떨까요?

주차 요금 vo 가 주차 예상 요금에도 쓰이는거 같아서요. 뭔가 공용적인 Fee 가 된 느낌?

2024-02-24 08:34 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/TimeInfo.java
> +            return today.calculateOverlapMinutes(beginTime, endTime) + tomorrow.calculateOverlapMinutes(beginTime, endTime);
다른 곳에서 안쓰이는 메서드 같은데 맞다면 private 도 괜찮아 보입니다!

2024-02-24 08:34 UTC, youngh0 commented on src/main/java/com/example/parking/domain/parking/FeePolicy.java
> +        minutes = minutes - baseTimeUnit.getTimeUnit();
minutes -= baseTimeUnit.getTimeUnit(); 로도 가능할듯하네요

2024-02-24 08:34 UTC, youngh0 commented on src/test/java/com/example/parking/domain/parking/FreeOperatingTimeTest.java
> +    static Stream<Arguments> getFreeOperatingTime() {
친절하시네요 ㅎ

2024-02-24 08:34 UTC, youngh0 commented on src/test/java/com/example/parking/domain/parking/ParkingTest.java
> +class ParkingTest {
다시 복구됐군요 GOOD

2024-02-25 16:40 UTC, This2sho reviewed
요금 계산 로직이 쉽자 않았는데 테스트까지 꼼꼼하게 잘 짜셨네유(주석있어서 이해하기도 편했슴다)👍
테스트 케이스 직접 계산해보면서 틀린 부분은 없었고 엣지 케이스로 종료시간이 23:59분일때 확인할려고 했는데 잘 짜두셨네유 👍

몇 가지 댓글만 남겼는데, 반영하실거만 해서 머지해도 될거 같슴다

2024-02-26 14:39 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/ParkingFeeCalculator.java
> +public class ParkingFeeCalculator {
현재 사용하지 않아, 빈 등록은 하지 않았습니다.

이걸 사용하는 측에서 빈등록해서 사용하시면 될 것 같습니다 !

2024-02-26 14:42 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/ParkingFeeCalculator.java
> +    public Fee calculateParkingFee(Parking parking, LocalDateTime beginTime, LocalDateTime endTime) {
사실 `Money` 와 동등하게 생각했는데요.

돈을 한 번 묶은 VO라고 생각하는데, 요금을 나타내기 위한 수단이라고 생각했어요.

크게 주차 요금 또한 요금이고 주차 예상 요금 또한 요금이고, 만약 전기차 충전 가격을 매긴다면, 그것 또한 요금이 될 수 있다고 생각했습니다. 

그렇기에 `Fee`안에는 주차와 관련된 메서드가 없습니다. 단지, 돈이 유효한지 (돈 >= 0) 또한 돈 더하기, 곱하기 등 돈 계산 메서드만 들어가있어 무리가 없다고 생각했습니다.

어떻게 생각하시는지요 ?

2024-02-26 14:43 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/TimeInfo.java
> +            return today.calculateOverlapMinutes(beginTime, endTime) + tomorrow.calculateOverlapMinutes(beginTime, endTime);
어떤 메서드를 말씀하시는걸까요 ?
`calculateOverlapMinutes`는 내부적으로 호출하기도 하지만 외부에서도 호출합니다 !

겹치는 시간이 몇분인지 구하는 것이지여

2024-02-26 14:47 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/DayParking.java
> +    private LocalTime endTime;
사실 이부분은 `TimeInfo`를 재활용할까 고민했습니다.

지금 생각해보니 결국 시작시간 ~ 종료 시간을 나타내는 객체에 해당하므로 써도 될 것 같기도하고...?

더 깔끔해질것같기도하고요.. 흠..

2024-02-26 14:48 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/TimeInfo.java
> +            return localTime.getHour() * 60 + localTime.getMinute() + 1;
만약 자정을 의미하고 싶다면 LocalTime.MAX를 무적권 써야됩니다..!

그래야 이 로직에 걸려서요 .ㅋㅋㅋ

2024-02-26 14:49 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/parking/FreeOperatingTime.java
> +    public int calculatePayOfChargeMinutes(DayParking dayParking) {
`Charge`라는 단어가 충전으로 해석될 여지가 있어서 변경하자는 말씀이신가요 !?

2024-02-26 17:13 UTC, merged