Feat/#19 리뷰 관리 기능 구현
parkingkim/parking-BE pull request #33
Opened 2024-02-23 11:47 UTC by This2sho

## 👍관련 이슈
- close: #19 

## 🤔세부 내용
- 리뷰 작성하는 기능 구현 했습니다.
  - 이미지 저장하는 기능 구현했습니다. 
- #19 참고 해주세여

todo
- [x] 객체 참조 대신 id 참조로 변경
- [x] EnumList 변경 감지 작동하는지 테스트
- [x] Convert 어노테이션 필드에 붙이도록 변경

## 🫵리뷰 중점사항
- 내가 쓴 리뷰 조회, 주차장 상세보기에서 resonse 같은 경우는 스펙을 생각해보고 추가하겠습니다.
- 리뷰 작성 같은 경우는 테스트 해본다고 일단 만들었습니다.
- `MemberRepository` Fake 객체 만든다고 `JpaRepository`에서 `Repository`로 변경했는데 괜찮을까여?

2024-02-24 08:52 UTC, youngh0 requested changes
고생하셨습니다~

코멘트 확인부탁드립니다 ㅎ

2024-02-25 17:25 UTC, This2sho commented on src/test/java/com/example/parking/fake/BasicMemberRepository.java
> +    public List<Member> saveAndGet(int size) {
넴.. 생각보다 들어가는 인자가 복잡해서 임시로 만들어뒀습니다..

2024-02-25 17:31 UTC, This2sho commented on src/test/java/com/example/parking/auth/MemberSessionRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
`@DataJpaTest`로 돌리게되면 `EmbeddedDatabase`를 사용해서 테스트하기 때문에
Mysql로 테스트를 돌리면 오류가 발생해서 해당 어노테이션을 `EmbeddedDatabase`를 사용안하도록 해주는 옵션입니다.

2024-02-25 17:31 UTC, This2sho commented on src/test/java/com/example/parking/fake/BasicRepository.java
> +            Field field = entity.getClass().getDeclaredField("id");
FakeRepository에서 `id`를 설정해줄 방법이 없더라구여

2024-02-25 17:32 UTC, This2sho commented on src/test/java/com/example/parking/application/review/ReviewServiceTest.java
> +@ExtendWith(MockitoExtension.class)
그렇네유 삭제하겠슴다!

2024-02-25 17:32 UTC, This2sho commented on src/main/java/com/example/parking/domain/review/PrivateImageStorage.java
> +    public PrivateImageStorage(@Value("${file.dir}") String directory) {
녬~

2024-02-25 17:34 UTC, This2sho commented on src/main/java/com/example/parking/domain/review/Review.java
> +    @OneToMany(mappedBy = "review", cascade = CascadeType.PERSIST)
리뷰랑 이미지가 Database에서 같이지워져도 실제 이미지는 남아있어서 일단, PERSIST만 걸었습니다.

2024-02-26 07:35 UTC, jundonghyuk requested changes
고생하셨어요 건호형 커멘트 남겼으니 확인부탁드려요 ㅎㅅㅎ

2024-02-26 07:35 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/review/Review.java
> +
리뷰가 `Parking`과 `reviewer` 자체를 알아야 할 필요가 있을까요 ?

`id`만 갖고있어도 될 것 같은데, 너무 커플링이 되어있는것같아서 여쭙습니다..!

2024-02-26 07:35 UTC, jundonghyuk commented on src/test/java/com/example/parking/application/review/ReviewServiceTest.java
> +@ExtendWith(MockitoExtension.class)
모키토를 안쓰는것 같은데 맞나요 ?

2024-02-26 07:35 UTC, jundonghyuk commented on src/main/java/com/example/parking/domain/review/Review.java
> +    private List<Content> contents;
어노테이션 없이 이렇게 들어가면 디비 상으로는 어떻게 들어가는거죠 ?

Enum.String처리도 없어서 궁금해서 여쭙습니다.

2024-03-10 12:02 UTC, This2sho commented
[이후 커밋](https://github.com/parkingkim/parking-BE/pull/33/files/691c8471e4c0f9bbeed20079af1452a3cc0976c6..e5d010961be947d98e80f90311d270a7420bf4f2)

- 객체 참조 대신 id 참조로 변경
- 주차장 조회 구현
- Convert 어노테이션 필드에 붙이도록 변경

2024-03-12 14:23 UTC, jundonghyuk approved these changes

2024-03-12 14:36 UTC, merged