주차장 즐겨찾기
parkingkim/parking-BE pull request #38
Opened 2024-03-02 14:30 UTC by youngh0

## 👍관련 이슈
- close: #37 

## 🤔세부 내용
- 즐겨찾기 등록, 삭제 구현했습니다.
- 즐겨찾기에 있는 Member, Parking 은 AggregateReference 로 하고 싶었는데 잘 안되가지고 일단 값 객체 포장하고 @Embedded 사용했습니다. 

## 🫵리뷰 중점사항
### Favorite 내부에 Boolean isFavorite 을 두어 이걸 계속 업데이트해서 관리할지 고민입니다.
- 이 경우 첫 즐겨찾기 등록일 경우 insert, 두 번째 등록이거나 즐겨찾기 삭제면 update 를 해야됩니다.
- 즉, if 분기를 통해 동작이 달라지게 됩니다.
- 그래서 저는 service 로직의 분기문을 없애기 위해 즐겨찾기 등록, 삭제를 별도의 api 로 나누고 등록하는 service 메서드는 insert 만, 삭제하는 service 메서드는 delete 만 하도록 구현했습니다.
- 혹시 어떤 방법이 더 괜찮다고 생각하시나요? 

### Favorite 의 (memberId, parkingId) 를 조합한 unique 를 통해 중복 등록 막았습니다.
- 이 경우 그렇게 큰 예외상황은 아닌 것 같아서 try...catch 문에서 로그만 찍어놨습니다.

### service test
- 서비스 테스트는 인증코드 PR 에 데이터삭제하는 걸 구현해놔서 인증코드 PR 머지 후 추가하겠습니다!

2024-03-10 11:52 UTC, This2sho requested changes
고생하셨슴다 레오띠
제가 생각했을 때
클라이언트쪽에서 분기를 나누면(현재 상황) 클라이언트 요청 시점(보이는 시점)에 따라 데이터를 변경하는데 (사용자가 원하는대로 변경이 이뤄남)
서버쪽에서 분기를 나누면 클라이언트에서 보이는 시점과 다르게 데이터가 변경될 수도 있는거 같아서 
(사용자가 여러번 눌렀을 때, 원하는대로 변경이 안될수도있음)
즐겨찾기 현재 로직이 깔끔하고 괜찮은거 같습니다.

2024-03-10 11:52 UTC, This2sho commented on src/main/java/com/example/parking/application/favorite/FavoriteService.java
> +
```suggestion
```

2024-03-10 11:52 UTC, This2sho commented on src/main/java/com/example/parking/application/favorite/FavoriteService.java
> +            log.warn("memberId: {}, parkingId: {} request duplicate favorite create", favorite.getMemberId(), favorite.getParkingId());
로그찍고 컨트롤러에서 created 반환하는데 다른 예외 던져주는게 좋을거 같아유

2024-03-12 14:28 UTC, jundonghyuk approved these changes

2024-03-12 14:28 UTC, jundonghyuk commented on src/main/java/com/example/parking/api/favorite/FavoriteController.java
> +    }
favoriteId는 pathvariable로 받고, memberId는 토큰 파싱하면 나오지 않나요 ?

2024-03-12 15:16 UTC, merged