주소를 통한 좌표 변환 기능 구현
parkingkim/parking-BE pull request #6
Opened 2024-01-24 18:43 UTC by youngh0

## 👍관련 이슈
- close: #4 

## 🤔세부 내용
안녕하세용 첫 PR의 영광은 제가 가져가겠습니다 ㅎㅎ

- 좌표 변환 api는 카카오를 사용했습니다. api key 값은 저희 설정파일에 올리면 노출 위험이 있어서 일단 노션에 공유하고 추후 서브모듈 같은걸 사용해서 공유하면 될 것 같아요.

- 좌표 변환이 안되는 주소들이 있는데 이는 주소 변환 api 의 응답값 중 meta 필드의 totalCount 가 0인 경우입니다. 그래서 이 부분은 별도로 분기처리 했습니다.

## 🫵리뷰 중점사항
- 좌표 변환이 안되는 주소가 있습니다. 그래서 이 경우는 Coordinate 객체의 위도 경도 값인 (0,0) 더미 인스턴스를 반환하게 했습니다. 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.
    - 제가 생각한 방법은 1. `CoordinateService.extractCoordinateByAddress(String address)` 의 파라미터로 Parking 객체를 받고 기존 위도, 경도 값을 통해 Coordinate 인스턴스를 생성해 반환하는 것과, 2. 현재처럼 (0,0) 더미값을 반환하는 방법이에요.
    - 후자의 경우, 주차장 api 를 호출해 데이터를 가공하는 측에서, 변환한 Coordinate 이 더미값이면 기존의 위도 경도 값을 저장하는 식의 처리가 필요할 것 같습니다.

2024-01-28 13:15 UTC, jundonghyuk requested changes
고생하셨습니다 커멘트 다달았어용

2024-01-28 13:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/coordinate/CoordinateService.java
> +    private final Coordinate INVALID_COORDINATE = new Coordinate(0, 0);
이부분이 `Coordinate` 안으로 들어가도 될 것 같다는 생각입니다 !

2024-01-28 13:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/coordinate/CoordinateService.java
> +    private final RestTemplate restTemplate;
외부 API로 부터 응답이 지연되거나 안오는 케이스를 생각해볼수도있을것같아요.

빈에 등록되어있는 레스트템플릿빌더를 활용해서 컨피그 파일로 만들어줄 수 있을 것같아용

2024-01-28 13:15 UTC, jundonghyuk commented on src/main/java/com/example/parking/application/coordinate/CoordinateService.java
> +                .build();
이 파트도 `RestTemplateBuilder`를 활용하면 헤더 설정이 가능하지 않을까요 ?

2024-01-30 04:38 UTC, This2sho reviewed
고생하셨네여 레오
`좌표 변환 api는 카카오를 사용했습니다. `
-> 노션 API 관련 페이지에 작성 부탁드립니다

`좌표 변환이 안되는 주소가 있습니다.`
-> 이 부분은 주소가 있는데, 좌표가 변환안되는건가여?
기존에 주소나 좌표가 존재하는데 변환이 안되는 경우라면, 기존 좌표를 사용하는게 좋을 거 같습니다.
그게 아니라 주소가 없어서 좌표가 변환이 안되는 경우라면, 저희 서비스에서 못쓰는 데이터인데 버리는게 나을거 같아여

2024-01-31 15:01 UTC, youngh0 commented on src/main/java/com/example/parking/application/coordinate/Coordinate.java
> +public class Coordinate {
이 부분은 제가 Location 의 존재를 놓쳤네요 ㅎ..

2024-01-31 17:24 UTC, youngh0 commented on src/main/java/com/example/parking/application/coordinate/CoordinateService.java
> +                .build();
처음에는 RestTemplateBuilder 의 `defaultHeader` 를 사용해 생성자에서 "Authentication" 헤더를 기본으로 설정해주려고 했는데요. @Value 어노테이션은 빈 후처리기에 의해 동작하기 때문에 빈 인스턴스 생성시점(생성자)에는 @Value 어노테이션의 값이 null 이더라구요. 그래서 다른 방법을 찾아봤습니다.

찾아보니 `ClientHttpRequestInterceptor` 인터페이스를 구현한 인터셉터를 활용해서 request 객체를 조작할 수 있더라구요.
그래서 `CoordinateRestTemplateInterceptor` 를 통해 헤더 설정을 하도록 수정했습니다!

2024-01-31 17:25 UTC, youngh0 commented on src/main/java/com/example/parking/application/coordinate/CoordinateService.java
> +    private final RestTemplate restTemplate;
재시도 로직 같은 경우는 어떤 경우에 어떤 식으로 재시도할지 정해진게 없어서 냅뒀습니다!

2024-02-02 05:17 UTC, jundonghyuk approved these changes

2024-02-02 05:20 UTC, merged