Refactor/#66 스케줄러 모듈 분리
parkingkim/parking-BE pull request #68
Opened 2024-04-10 17:17 UTC by This2sho

## 👍관련 이슈
- close: #66 

## 🤔세부 내용
- [ ] 도메인 모듈 분리 (도메인, infra(DB 관련))
  - [ ] 의존성 확인
- [ ] API 모듈 분리 (컨트롤러, 어플리케이션 서비스 및 인증 관련)
  - [ ] 의존성 확인
- [ ] 스케줄러 모듈 분리
  - [ ] 의존성 확인
- [ ] CI 스크립트 수정
- [ ] CD 스크립트 수정
- [ ] 서버내 배포 스크립트 수정
- [ ] 서버내 docker-compose 수정

## 🫵리뷰 중점사항
- 의존성 잘 나눠졌는지 확인 부탁드립니다.
- 기존에 auth 부분이 패키지가 다른 것들과 달라서 모듈 분리하면서 수정했습니다. 확인 부탁드립니다
- session 같은 경우 Entity로 처리되어 있는데 추후에 redis 사용해서 api 모듈로 빼는게 괜찮아 보입니다.
- [ ] 예외가 domain에 몰려있는데 이 부분은 추후 수정이 필요할 거 같습니다.

2024-04-12 04:08 UTC, youngh0 requested changes
고생하셨습니다!

변경 범위가 넓고 모듈 변경에 의한 코드 재배치가 주인거같아서 클래스 위치랑 ci flow 에 대해서만 코멘트 남겼습니다!

PR 에 써주신 auth 내용도 확인했습니다. 😎

2024-04-12 04:08 UTC, youngh0 commented on app-api/src/main/java/com/parkingcomestrue/parking/application/exception/ClientException.java
> +public class ClientException extends RuntimeException {
Exception 부분은 domain 모듈처럼 별도의 support 패키지로 빼도 괜찮을거같아요.

2024-04-12 04:08 UTC, youngh0 commented on app-api/src/test/java/com/parkingcomestrue/parking/application/config/TestConfig.java
이 클래스는 application 패키지랑 동등한 레벨의 config 패키지로 빠져도 좋아보입니다.

2024-04-12 04:08 UTC, youngh0 commented on app-api/src/test/java/com/parkingcomestrue/parking/application/container/ContainerTest.java
요것도 application 패키지랑 동등한 레벨로 빠져도 좋을듯요

2024-04-12 04:08 UTC, youngh0 commented on app-scheduler/src/main/java/com/parkingcomestrue/external/config/ParkingApiErrorHandler.java
이건 external 패키지 아래에 있는 클래스 전부에 대한 내용입니다.

모든 패키지가 external 패키지 하위에 있어서 external 패키지가 없어도 괜찮을 거 같아요.
뎁스만 하나 추가된 느낌?

2024-04-12 07:46 UTC, youngh0 commented on app-scheduler/src/main/java/com/parkingcomestrue/external/scheduler/ParkingUpdateScheduler.java
>      public void autoUpdateOfferCurrentParking() {
저 이거 이제 봤는데 혹시 @Transactional 일부러 안붙인건가요??

2024-04-12 08:20 UTC, This2sho commented on .github/workflows/ci.yml
> +          if git diff --name-only origin/main...HEAD | grep -q "^domain/"; then
저도 처음에 `path` 로 트리거를 하고 모듈 별로 ci를 따로 하려고 했는데
그러면 다음과 같은 문제가 생깁니다.
1. 테스트 수행을 제외한 이외의 `step`이 동일한데, 중복이 발생한다.
2. 테스트가 중복된다. (Domain모듈이 변경되는 경우, Domain을 의존하는 API, Scheduler가 같이 테스트 되어야하는데 path로 트리거를 하고 Domain 및 API 가 변경되면 Domain에서도 API를 테스트하고, API 모듈에서도 API를 테스트하게 됩니다)
3. 테스트 결과를 모아서 볼 수가 없다.

2024-04-12 08:35 UTC, This2sho commented on app-scheduler/src/main/java/com/parkingcomestrue/external/config/ParkingApiErrorHandler.java
스프링 패키지 구조에서 `com-회사 도메인-프로젝트명` 이 관례로 알고 있습니다.
여기서 exteranl은 프로젝트 명으로 사용했는데, 다른 네이밍 있으면 추천해주세여

추가로 `scanBasePackages`로 하고 있다가 [우형 멀티모듈](https://techblog.woowahan.com/2637/) 보고 
Application을 상위 패키지(parkingcomestrue)로 올리는게 조금 더 확장성 있다고 생각해서 바꿨습니다.

2024-04-12 08:43 UTC, This2sho commented on app-scheduler/src/main/java/com/parkingcomestrue/external/scheduler/ParkingUpdateScheduler.java
>      public void autoUpdateOfferCurrentParking() {
![image](https://github.com/parkingkim/parking-BE/assets/48519860/2fceb838-449d-491d-ae9c-f1359d3837d4)

ㅋ_ㅋ 피드백 받고 #31 에서 뺐습니다.

2024-04-12 08:53 UTC, youngh0 commented on app-scheduler/src/main/java/com/parkingcomestrue/external/scheduler/ParkingUpdateScheduler.java
>      public void autoUpdateOfferCurrentParking() {
저 코멘트는 트랜잭션 범위에서 외부 api 통신하는 코드를 빼는 의도였는데 변경된 부분을 제가 리뷰하면서 놓쳤나봐요.

autoUpdateOfferCurrentParking 메서드 전체를 트랜잭션으로 묶는게 아니라 autoUpdateIfferCurrentParking 메서드의 readBy 아랫부분을 트랜잭션 범위로 묶는게 좋아보여요.

현재는 readBy 로 조회한 주차장 별로 커넥션 획득 -> 커밋 -> 해제가 발생할거같아요

이 부분은 모듈 분리랑은 거리가 있으니 이 PR 머지되고 수정해도 될 것 같아요.

2024-04-12 09:04 UTC, This2sho commented on app-scheduler/src/main/java/com/parkingcomestrue/external/scheduler/ParkingUpdateScheduler.java
>      public void autoUpdateOfferCurrentParking() {
전체 주차장 조회를 하나의 트랜잭션으로 묶으란 말씀인가여?

2024-04-16 10:27 UTC, jundonghyuk approved these changes

2024-04-16 12:14 UTC, youngh0 approved these changes

2024-04-16 12:35 UTC, merged